/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing_practice;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

        





/**
 *
 * @author Boruto
 */
public class Billing_v1 extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrame2
     */
    public Billing_v1() {
        

        initComponents();
        
        
//        DefaultTableModel tb_model = (DefaultTableModel) customer_order_tb.getModel();
//        
//        tb_model.setValueAt(23, 0, 1);
  
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableMenu = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        flavors_BG = new javax.swing.JPanel();
        okinawa_fv = new javax.swing.JButton();
        hazlenut_fv = new javax.swing.JButton();
        hokkaido_fv = new javax.swing.JButton();
        caramel_fv = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_order_tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        grand_total = new javax.swing.JLabel();

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        tableMenu.add(delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1390, 768));

        BG.setBackground(new java.awt.Color(150, 96, 18));

        flavors_BG.setOpaque(false);
        flavors_BG.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        okinawa_fv.setText("OKINAWA");
        okinawa_fv.setOpaque(true);
        okinawa_fv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okinawa_fvActionPerformed(evt);
            }
        });
        flavors_BG.add(okinawa_fv);

        hazlenut_fv.setText("HAZLENUT");
        hazlenut_fv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hazlenut_fvActionPerformed(evt);
            }
        });
        flavors_BG.add(hazlenut_fv);

        hokkaido_fv.setText("HOKKAIDO");
        hokkaido_fv.setToolTipText("");
        flavors_BG.add(hokkaido_fv);

        caramel_fv.setText("CARAMEL");
        flavors_BG.add(caramel_fv);

        customer_order_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flavor", "Size", "Price", "Add pearl", "Add CreamCheese", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        customer_order_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_order_tbMouseClicked(evt);
            }
        });
        customer_order_tb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                customer_order_tbPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(customer_order_tb);

        jLabel1.setText("GRAND TOTAL :");

        grand_total.setText("GRAND TOTAL :");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(flavors_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(grand_total, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flavors_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grand_total, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okinawa_fvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okinawa_fvActionPerformed
     
        Billing.show_AddOrderJFrame(new AddOrder(), "Okinawa", AddOrder.flavor);
        
      
    }//GEN-LAST:event_okinawa_fvActionPerformed

    private void hazlenut_fvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hazlenut_fvActionPerformed
        Billing.show_AddOrderJFrame(new AddOrder(), "Hazlenut", AddOrder.flavor);
    }//GEN-LAST:event_hazlenut_fvActionPerformed

    private void customer_order_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_order_tbMouseClicked
        PopupMenu.showMenu(evt, customer_order_tb, tableMenu);
      
      
    }//GEN-LAST:event_customer_order_tbMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        PopupMenu.delete(customer_order_tb);
    }//GEN-LAST:event_deleteActionPerformed

    private void customer_order_tbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_customer_order_tbPropertyChange
        
 
    }//GEN-LAST:event_customer_order_tbPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            public void run() {
                
                new Billing_v1().setVisible(true);
                
     
         
            }
            
                      
                     
        });
        
        


      
    }
    

 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton caramel_fv;
    public static javax.swing.JTable customer_order_tb;
    private javax.swing.JMenuItem delete;
    private javax.swing.JPanel flavors_BG;
    public static javax.swing.JLabel grand_total;
    private javax.swing.JButton hazlenut_fv;
    private javax.swing.JButton hokkaido_fv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okinawa_fv;
    private javax.swing.JPopupMenu tableMenu;
    // End of variables declaration//GEN-END:variables

    
    
    //Edit UI of column in Jtable
    public static void changeJtableHeaderColor(JTable table, Color color)
    {
         DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
         MyHeaderRender.setBackground(color);
         
         int col_count = table.getColumnCount();
         
         for(int i = 0; i < col_count; i++)
         {
             
             table.getTableHeader().getColumnModel().getColumn(i).setHeaderRenderer(MyHeaderRender);
              
         } 
            
    }
    

}

